[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".vscode",
    "__pycache__",
    "*.pyc",
    ".cache",
    "archive",
    "books",
    "test_data",
    ".env",
    "*.egg-info",
]

# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
# Enable pycodestyle (`E`), Pyflakes (`F`), and isort (`I`)
select = ["E", "F", "I", "N", "W", "UP", "B", "A", "C4", "SIM"]

# Ignore specific rules
ignore = [
    "E501",  # Line too long (handled by formatter)
    "E203",  # Whitespace before ':'
    "F401",  # Imported but unused (sometimes needed for side effects)
    "F841",  # Local variable assigned but never used
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Use double quotes for strings.
quote-style = "double"

# Indent with spaces, not tabs.
indent-style = "space"

# Respect line endings
line-ending = "auto"

# Enable magic trailing comma
skip-magic-trailing-comma = false

[tool.ruff.lint.isort]
known-first-party = ["src", "tests", "download"]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
# Tests can have unused imports and long lines
"tests/*.py" = ["F401", "E501"]
"*/__init__.py" = ["F401"]